###data from:http://portal.ncdenr.org/web/mf/fish-common-names-list
c(
  "Albacore",
  "Amberjack",
  "Bank Sea Bass",
  "Barracuda",
  "Bigeye Tuna",
  "Blackfin Tuna",
  "Black Drum",	
  "Black Sea Bass",	
  "Blacktip Shark",	
  "Bluefish",	
  "Bluefin Tuna",
  "Blue Marlin",
  "Blueline Tilefish",	
  "Butterfish",	
  "Cobia",	
  "Croaker",	
  "Dolphin",
  "Flounder",
  "Hogfish",
  "Pigfish",	
  "Pinfish",
  "Skate",
  "Scamp",
  "Spot",
  "Wahoo",
  "Yellowfin Tuna	",
  "Stingray",
  "Sea Mullet",
  "Pompano"
  )